### ISSUE TITLE
[BUG] Andorid build error

### ISSUE THREAD

**Issue by vasilich6107** [surfstudio/flutter-push-notification#27]
Could not resolve ru.surfstudio.android:push:0.4.0.
     Required by:
         project :app > project :push_notification

**Comment by MbIXjkee** [comment]
@vasilich6107 Hi! Sorry, but I'm not able to fix this, because I don't work more in the organization. You can write to the team in the telegram by the link in the readme file.

**Comment by mark-kascheev** [comment]
Hello, @vasilich6107! Sorry for not responding, I think we fixed the problem.
Thanks for the help!

**Comment by B0yma** [comment]
```
  defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.push_demo"
        minSdkVersion 19
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }
   ``` 
   in your example targetSdkVersion  = 28
   if we change to 31 or above app crashes with error:
   ```
   E/AndroidRuntime( 8723): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
E/AndroidRuntime( 8723): 	at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
E/AndroidRuntime( 8723): 	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
E/AndroidRuntime( 8723): 	at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
E/AndroidRuntime( 8723): 	at ru.surfstudio.android.notification.ui.notification.strategies.PushHandleStrategy.preparePendingIntent(PushHandleStrategy.kt:237)
E/AndroidRuntime( 8723): 	at ru.surfstudio.android.notification.ui.notification.strategies.PushHandleStrategy.handle(PushHandleStrategy.kt:161)
E/AndroidRuntime( 8723): 	at pushnotification.push_notification.handler.PushHandler.handleMessage(PushHandler.kt:20)
E/AndroidRuntime( 8723): 	at pushnotification.push_notification.PushNotificationPlugin.handleNotification$lambda-0(PushNotificationPlugin.kt:128)
E/AndroidRuntime( 8723): 	at pushnotification.push_notification.PushNotificationPlugin.$r8$lambda$RGpar5Gn70ioPnKOFsbr8ZdTorM(Unknown Source:0)
E/AndroidRuntime( 8723): 	at pushnotification.push_notification.PushNotificationPlugin$$ExternalSyntheticLambda0.run(Unknown Source:6)
E/AndroidRuntime( 8723): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
E/AndroidRuntime( 8723): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime( 8723): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime( 8723): 	at java.lang.Thread.run(Thread.java:920)
```
how to fix?

**Comment by tinted-knight** [comment]
Hi @vasilich6107. Do you still face your original issue or the one @B0yma mentioned above?
